### ISSUE TITLE
Tree Feller.

### ISSUE THREAD

**Issue by aWitch-Doctor** [Daniel12321/AdventureMMO#24]
In your latest version 2.0.5, Tree feller is called tree veller and when it's used it only breaks 2 blocks above the block you break, not the whole tree. For 2x2 trees it only breaks 3 blocks total, the one you break and 2 above it.

**Comment by Daniel12321** [comment]
Ill test this right now

**Comment by Daniel12321** [comment]
Other than fact that i misspelled Tree Feller, everything seems to work as it should. Can you try updating your sponge and see if the problem still occurs?

**Comment by aWitch-Doctor** [comment]
I am running the latest version of sponge 1.10.2-5.2.0-BETA-383, The email I sent you has a list of all the other plugins im running if you need them.

I was informed that you may have built the plugin off of sponge api 6, if this is the case will there be a release for api 5?

Here is the error from the log, i am only coping the error itself. If you need more let me know. This pops up for every log you break regardless of tree size or location on the tree.


[16:48:06] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task adventuremmo-S-1017 owned by Plugin{id=adventuremmo, name=AdventureMMO, version=2.0.5, description=A light-weight plugin that adds skills with all sorts of fun game mechanics to your server., authors=[Daniel12321], source=mods/AdventureMMO-v2.0.5.jar}, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.world.Location.createEntity(Lorg/spongepowered/api/entity/EntityType;)Lorg/spongepowered/api/entity/Entity;
	at me.mrdaniel.adventuremmo.utils.ItemUtils.drop(ItemUtils.java:46) ~[ItemUtils.class:?]
	at me.mrdaniel.adventuremmo.listeners.skills.WoodcuttingListener.lambda$null$0(WoodcuttingListener.java:54) ~[WoodcuttingListener.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_72-internal]
	at me.mrdaniel.adventuremmo.listeners.skills.WoodcuttingListener.lambda$null$1(WoodcuttingListener.java:50) ~[WoodcuttingListener.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_72-internal]
	at me.mrdaniel.adventuremmo.listeners.skills.WoodcuttingListener.lambda$onBlockBreak$2(WoodcuttingListener.java:48) ~[WoodcuttingListener.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:84) ~[SyncScheduler.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-5.2.0-BETA-383]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_72-internal]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51) [SyncScheduler.class:1.10.2-5.2.0-BETA-383]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-5.2.0-BETA-383]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onTick$znp000(SourceFile:1253) [ld.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:340) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by Daniel12321** [comment]
The newest version, v2.0.6, includes a download for each of API 4, 5 and 6. The name of Tree Feller is also fixed. Considered closed.
