### ISSUE TITLE
Failed to save player data!

### ISSUE THREAD

**Issue by BreeOge** [Daniel12321/AdventureMMO#40]
For some reason this mod is causing issues.  After about 5 to 10 min of playing it starts pumping out 
Failed to save Player Data
After it does this, if ANY player disconnects it will crash the server..  Here is the error log where it happens..
`[20:24:38] [Server thread/WARN]: Failed to save player data for BreeOge
[20:25:19] [Server thread/INFO]: BreeOge lost connection: Disconnected
[20:25:19] [Server thread/INFO]: BreeOge left the game
[20:25:19] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.api.data.DataRegistrationNotFoundException
	at org.spongepowered.common.data.SpongeManipulatorRegistry.getRegistrationFor(SpongeManipulatorRegistry.java:149) ~[SpongeManipulatorRegistry.class:1.11.2-2282-7.0.0-BETA-2301]
	at org.spongepowered.common.data.util.DataUtil.getRegistrationFor(DataUtil.java:429) ~[DataUtil.class:1.11.2-2282-7.0.0-BETA-2301]
	at org.spongepowered.common.data.util.DataUtil.getSerializedManipulatorList(DataUtil.java:132) ~[DataUtil.class:1.11.2-2282-7.0.0-BETA-2301]
	at net.minecraft.entity.Entity.writeToNbt(Entity.java:5748) ~[sn.class:?]
	at net.minecraft.entity.EntityLivingBase.writeToNbt(EntityLivingBase.java:3142) ~[sw.class:?]
	at net.minecraft.entity.Entity.handler$onWriteToNBT$zcm000(Entity.java:5652) ~[sn.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java) ~[sn.class:?]
	at net.minecraft.server.management.PlayerList.handler$onPlayerLogOut$zhk000(PlayerList.java:1980) ~[mt.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java) ~[mt.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:795) ~[mi.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:455) ~[er.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) ~[mh.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[20:25:19] [Server thread/ERROR]: This crash report has been saved to: /home/AMP/.ampdata/instances/MCMA/Minecraft/./crash-reports/crash-2017-05-03_20.25.19-server.txt
[20:25:19] [Server thread/INFO]: Stopping server
[20:25:19] [Server thread/INFO]: Saving players
[20:25:19] [Server thread/WARN]: Failed to save player data for BreeOge
[20:25:19] [Server thread/WARN]: handleDisconnection() called twice`

**Comment by WryWolfy** [comment]
I've had the same issue.  It seems to begin when a player levels up a skill.
Using SpongeVanilla.

**Comment by BreeOge** [comment]
The problem is, if you keep letting it go, your world gets corrupt.
