### ISSUE TITLE
Start error and player data not saved

### ISSUE THREAD

**Issue by Parilar** [Daniel12321/AdventureMMO#42]
If i use the plugin player data is not saved

 [20:17:46] [Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=adventuremmo, name=AdventureMMO, version=2.0.7, description=A light-weight plugin that adds skills with all sorts of fun game mechanics to your server., authors=[Daniel12321], source=/home/ddc/minecraft/./mods/plugins/AdventureMMO-v2.0.7-API6.x.jar}
java.lang.NullPointerException: Data name is null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.11.2.jar:?]
        at org.spongepowered.common.data.SpongeDataRegistration.<init>(SpongeDataRegistration.java:53) ~[SpongeDataRegistration.class:1.11.2-2282-6.1.0-BETA-2343]
        at org.spongepowered.common.data.SpongeDataRegistrationBuilder.buildAndRegister(SpongeDataRegistrationBuilder.java:158) ~[SpongeDataRegistrationBuilder.class:1.11.2-2282-6.1.0-BETA-2343]
        at org.spongepowered.common.data.SpongeDataManager.register(SpongeDataManager.java:268) ~[SpongeDataManager.class:1.11.2-2282-6.1.0-BETA-2343]
        at me.mrdaniel.adventuremmo.AdventureMMO.onPreInit(AdventureMMO.java:111) ~[AdventureMMO.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_AdventureMMO_onPreInit2.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-6.1.0-BETA-2343]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.11.2-2282-6.1.0-BETA-2343]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:212) [SpongeMod.class:1.11.2-2282-6.1.0-BETA-2343]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Jay9519** [comment]
confirm, I'm getting the same errors

AdventureMMO-v2.0.7-API6.x
SpongeForge-1.11.2-2282-6.1.0-BETA-2357

any solution for this?
