### ISSUE TITLE
Could not locate a DataRegistration for class class me.mrdaniel.adventuremmo.data.manipulators.MMOData

### ISSUE THREAD

**Issue by dmgm** [Daniel12321/AdventureMMO#44]
Hi, 

Brand new vanilla sponge server being run through msm.
Crashes seem random yet frequent. Particularly when someone logs out. 3 Example crash logs attached to show frequency and details.

Description: Exception in server tick loop

org.spongepowered.api.data.DataRegistrationNotFoundException: Could not locate a DataRegistration for class class me.mrdaniel.adventuremmo.data.manipulators.MMOData
        at org.spongepowered.common.data.SpongeManipulatorRegistry.getRegistrationFor(SpongeManipulatorRegistry.java:149)
        at org.spongepowered.common.data.util.DataUtil.getRegistrationFor(DataUtil.java:429)
        at org.spongepowered.common.data.util.DataUtil.getSerializedManipulatorList(DataUtil.java:132)
        at net.minecraft.entity.Entity.writeToNbt(SourceFile:5044)
        at net.minecraft.entity.EntityLivingBase.writeToNbt(SourceFile:2547)
        at net.minecraft.entity.Entity.handler$onWriteToNBT$zci000(SourceFile:4948)
        at net.minecraft.entity.Entity.func_189511_e(SourceFile)
        at net.minecraft.server.management.PlayerList.handler$onPlayerLogOut$zhg000(SourceFile:1770)
        at net.minecraft.server.management.PlayerList.func_72367_e(SourceFile)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(SourceFile:735)
        at net.minecraft.network.NetworkManager.func_179293_l(SourceFile:382)
        at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:215)
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1603)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:335)
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562)
        at net.minecraft.server.MinecraftServer.run(SourceFile:466)
        at java.lang.Thread.run(Thread.java:748)

[crash-2017-06-06_08.15.14-server.txt](https://github.com/Daniel12321/AdventureMMO/files/1053819/crash-2017-06-06_08.15.14-server.txt)
[crash-2017-06-06_13.17.26-server.txt](https://github.com/Daniel12321/AdventureMMO/files/1053821/crash-2017-06-06_13.17.26-server.txt)
[crash-2017-06-06_14.12.51-server.txt](https://github.com/Daniel12321/AdventureMMO/files/1053820/crash-2017-06-06_14.12.51-server.txt)

**Comment by dmgm** [comment]
Upgrading sponge vanilla to the latest beta seems to have fixed the problem.
No crashes anyhow which was my issue.
