### ISSUE TITLE
Errors AFTER removing this plugin entirely

### ISSUE THREAD

**Issue by ultracasual** [Daniel12321/AdventureMMO#47]
This is extremely frustrating. I even reinstalled forge fresh. Why does this plugin even do this???

> [21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: org.spongepowered.api.data.persistence.InvalidDataException: Could not translate me.mrdaniel.adventuremmo.data.manipulators.MMOData! Don't worry though, we'll try to translate the rest of the data.
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:147)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:226)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:101)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:212)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:96)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:66)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.entity.Entity.getUserForUuid(Entity.java:7603)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.entity.Entity.getNotifierUser(Entity.java:7570)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:149)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjp000(WorldServer.java:2820)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.World.func_72866_a(World.java:4072)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.World.func_72870_g(World.java:1934)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.World.func_72939_s(World.java:6002)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2162)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[21:14:29] [Server thread/INFO] [STDERR/]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:148]: 	at java.lang.Thread.run(Thread.java:748)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: me.mrdaniel.adventuremmo.data.manipulators.MMOData
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.forName0(Native Method)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.Class.forName(Class.java:264)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:138)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:634]: 	... 19 more
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:14:29] [Server thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 24 more<

**Comment by Revvilo** [comment]
There's probably some left over files inside the config/sponge folder... check that out.

**Comment by WaterMonitor** [comment]
I also have this issue
 someone help!

**Comment by fusionmc-evilscoop** [comment]
Its not left over configs etc, I believes its data encoded in the playerdata file under some key or other...

Im getting the same issue

If you open the player data in nbt explorer you can find the key, for me this was in SpongeData, custom manipultors there is a DataClass key of me.mrdaniel.adventuremmo.data.manipulators.MMOData

Removing this key causes server to crash though
