### ISSUE TITLE
A problem in console with forge and sponge 1.12.2

### ISSUE THREAD

**Issue by DavidForge** [Daniel12321/AdventureMMO#59]
[02:28:49] [Server thread/ERROR] [Sponge]: Could not pass DamageEntityEvent$Impl to Plugin{id=adventuremmo, name=AdventureMMO, version=2.0.7, description=A light-weight plugin that adds skills with all sorts of fun game mechanics to your server., authors=[Daniel12321], source=/root/PCN/PrismaMods/mods/AdventureMMO-v2.0.7-API4.x.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/entity/projectile/Arrow
        at me.mrdaniel.adventuremmo.listeners.skills.ArcheryListener.onDamage(ArcheryListener.java:46) ~[ArcheryListener.class:?]
        at org.spongepowered.common.event.listener.DamageEntityEventListener_ArcheryListener_onDamage60.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.entity.EntityLivingBase.damageEntityHook(EntityLivingBase.java:3626) [vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3457) [vp.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66) [zv.class:?]
        at net.minecraft.entity.passive.EntityWolf.func_70652_k(EntityWolf.java:353) [aam.class:?]
        at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178) [xo.class:?]
        at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167) [xo.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
        at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) [vd.class:?]
        at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) [zv.class:?]
        at net.minecraft.entity.passive.EntityWolf.func_70636_d(EntityWolf.java:212) [aam.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
        at net.minecraft.entity.passive.EntityWolf.func_70071_h_(EntityWolf.java:230) [aam.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:170) [TrackingUtil.class:1.12.2-2655-7.1.0-BETA-3024]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zll000(WorldServer.java:2878) [oo.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:4151) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1952) [amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6574) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2221) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by DavidForge** [comment]
I removed the plugin because it was spreading all the time with the console failure, please help me as soon as possible, thanks

**Comment by Buzz1971** [comment]
have you been able to sort out what is causing this error message I too am having the same issue

**Comment by Sparky200** [comment]
1.12.2 was released after this plugin's latest release. Should work on 1.11.x and lower.
