### ISSUE TITLE
MMoKeys

### ISSUE THREAD

**Issue by giopalma** [Daniel12321/AdventureMMO#63]
[16-07-2019 16:35:34] TsuNaMyITA ran the command: /skills
[16-07-2019 16:35:34] Error occurred while executing command 'skills' for source EntityPlayerMP['TsuNaMyITA'/133, l='pixelmon-reforged-7-0-6', x=29402.65, y=63.00, z=-27268.94]: Could not initialize class me.mrdaniel.adventuremmo.data.MMOKeys
[16-07-2019 16:35:34] java.lang.NoClassDefFoundError: Could not initialize class me.mrdaniel.adventuremmo.data.MMOKeys
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.data.manipulators.MMOData.registerGettersAndSetters(MMOData.java:43) ~[MMOData.class:?]
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.data.manipulators.MMOData.<init>(MMOData.java:38) ~[MMOData.class:?]
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.data.manipulators.MMOData.<init>(MMOData.java:29) ~[MMOData.class:?]
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.managers.MenuManager.sendSkillList(MenuManager.java:44) ~[MenuManager.class:?]
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.commands.CommandSkills.execute(CommandSkills.java:25) ~[CommandSkills.class:?]
[16-07-2019 16:35:34] at me.mrdaniel.adventuremmo.commands.PlayerCommand.execute(PlayerCommand.java:19) ~[PlayerCommand.class:?]
[16-07-2019 16:35:34] at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
[16-07-2019 16:35:34] at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
[16-07-2019 16:35:34] at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
[16-07-2019 16:35:34] at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
[16-07-2019 16:35:34] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
[16-07-2019 16:35:34] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
[16-07-2019 16:35:34] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
[16-07-2019 16:35:34] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
[16-07-2019 16:35:34] at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
[16-07-2019 16:35:34] at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
[16-07-2019 16:35:34] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
[16-07-2019 16:35:34] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
[16-07-2019 16:35:34] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
[16-07-2019 16:35:34] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
[16-07-2019 16:35:34] at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
[16-07-2019 16:35:34] at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
[16-07-2019 16:35:34] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
[16-07-2019 16:35:34] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
[16-07-2019 16:35:34] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
[16-07-2019 16:35:34] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
[16-07-2019 16:35:34] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
![Cattura](https://user-images.githubusercontent.com/33783684/61303458-d2f3fc80-a7e7-11e9-9bd1-ed01b509c7f5.PNG)

this is what happen when i try to do /skills with this plugin for sponge 1.12.2
can somone help me ?

**Comment by Luckfiend99** [comment]
This is exactly what happened to me. What I ended up doing, was just download a different version of the Plugin until I found the one that worked.

**Comment by Luckfiend99** [comment]
Get this version, it's the one that works for me on 1.12.2
MMO-v1.6.0-5.0.0.jar
