### ISSUE TITLE
Player data not stored

### ISSUE THREAD

**Issue by DHLF** [Daniel12321/AdventureMMO#8]
When I disconnect from my server this is written in the log file:
[13:03:04 ERROR] [adventuremmo]: Error while saving player file
[13:03:04 ERROR] [STDERR]: java.io.IOException: "File or Path not found"
[13:03:04 ERROR] [STDERR]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[13:03:04 ERROR] [STDERR]:        at java.io.File.createNewFile(File.java:1012)
[13:03:04 ERROR] [STDERR]:        at me.mrdaniel.mmo.io.players.MMOPlayerDatabase.save(MMOPlayerDatabase.java:113)

server: debian jessie (8)
gameserver version:  minecraft_server.1.10.2.jar + spongevanilla-1.10.2-6.0.0-BETA-149.jar
pluginversion: MMO-v1.6.1-1.10.2.jar 
java: openjdk version "1.8.0_111"

I tried to change /config/adventuremmo (and its contempts) from 644 to 755 but this did not help.
For linux a file named playerdata is different from Playerdata(capital letter). Could this be the cause?

Anyway the stats are not saved.

**Comment by Daniel12321** [comment]
Fixed in the newest version.
